apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: mongo-pvc, namespace: shopsphere }
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: shopsphere
  labels: { app: mongo }
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels: { app: mongo }
  template:
    metadata:
      labels: { app: mongo }
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports: [{ containerPort: 27017 }]
          env:
            - name: MONGO_INITDB_DATABASE
              value: shopsphere
          volumeMounts:
            - { name: mongo-data, mountPath: /data/db }
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
          readinessProbe:
            exec: { command: ["mongosh", "--eval", "db.adminCommand('ping')"] }
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: mongo-data
          persistentVolumeClaim: { claimName: mongo-pvc }
---
apiVersion: v1
kind: Service
metadata: { name: mongo, namespace: shopsphere, labels: { app: mongo } }
spec:
  clusterIP: None
  selector: { app: mongo }
  ports: [{ port: 27017, targetPort: 27017 }]
