apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopsphere
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Cloud-Tamil/Application-Projects.git'
    targetRevision: 8b699d8077efbb1c1e884773b5003637a5e73498
    path: ShopSphere - Microservices Application/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shopsphere
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
